// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A quip generation AI agent.
 *
 * - generateQuip - A function that handles the quip generation process.
 * - GenerateQuipInput - The input type for the generateQuip function.
 * - GenerateQuipOutput - The return type for the generateQuip function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateQuipInputSchema = z.object({
  topic: z.string().describe('The topic for which to generate a quip.'),
});
export type GenerateQuipInput = z.infer<typeof GenerateQuipInputSchema>;

const GenerateQuipOutputSchema = z.object({
  quip: z.string().describe('The generated quip.'),
});
export type GenerateQuipOutput = z.infer<typeof GenerateQuipOutputSchema>;

export async function generateQuip(input: GenerateQuipInput): Promise<GenerateQuipOutput> {
  return generateQuipFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateQuipPrompt',
  input: {schema: GenerateQuipInputSchema},
  output: {schema: GenerateQuipOutputSchema},
  prompt: `You are a quip generator. Generate a humorous quip about the following topic: {{{topic}}}`,
});

const generateQuipFlow = ai.defineFlow(
  {
    name: 'generateQuipFlow',
    inputSchema: GenerateQuipInputSchema,
    outputSchema: GenerateQuipOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
